#!/usr/bin/env node
/* Auto-generated by @alife/framework-checker/backend-runtime. Do not edit. */
import { readFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import http from 'node:http';
import { spawn } from 'node:child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const manifestPath = join(__dirname, 'runtime.json');
let manifest;
try {
  manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
} catch (err) {
  console.error('[backend-runtime] failed to read runtime.json:', err.message);
  process.exit(1);
}

const cwdAbs = resolve(__dirname, manifest.cwd || '.');
process.chdir(cwdAbs);

const envPort = parseInt(process.env.PORT, 10);
const PORT = Number.isFinite(envPort) && envPort > 0
  ? envPort
  : (typeof manifest.port === 'number' && manifest.port > 0 ? manifest.port : 3000);
process.env.PORT = String(PORT);

// ─── 进程级异常钩子 ─────────────────────────────────────────────────
// 装在所有用户代码加载之前，连用户的 uncaughtException 也能被捕获。
//
// 设计：log 后不主动 exit。
//   - FC 自定义容器是长生命周期进程，状态可能已损坏但 in-flight 的合法请求
//     还能完成；让 FC 的 health probe 决定是否回收，比盲目 exit 更稳。
//   - 真正的不可恢复异常会顺着 listener 链拒绝请求，FC 探活失败后会重启。
process.on('uncaughtException', (err) => {
  console.error('[backend-runtime] uncaughtException:', (err && err.stack) || err);
});
process.on('unhandledRejection', (reason) => {
  const detail = (reason && (reason.stack || reason.message)) || reason;
  console.error('[backend-runtime] unhandledRejection:', detail);
});

// 多层 default 解包：复刻 Vercel @vercel/node 的 5 次循环
//  - ESM 命名空间对象: { default: app, ... }
//  - CJS via dynamic import: { default: module.exports }
//  - TS→JS 编译可能再嵌一层 { default: { default: app } }
// 加 cur.default !== cur 判定避免自引用导致死循环
function unwrapDefault(mod) {
  let cur = mod;
  for (let i = 0; i < 5; i++) {
    if (cur && typeof cur === 'object' && cur.default !== undefined && cur.default !== cur) {
      cur = cur.default;
    } else break;
  }
  return cur;
}

// ─── Web Standard IO adapter ─────────────────────────────────────────
// 让用户写的 fetch handler / 命名 GET/POST/... 也能在 Node http.Server 下跑。
// 对应 Vercel @vercel/node 的 helpers-web.ts。
//
// 要求 globalThis.Request / Response / Headers / ReadableStream（Node 18+ 默认有）。

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'];

function buildWebRequest(req) {
  const proto = req.headers['x-forwarded-proto'] || 'http';
  const host = req.headers.host || 'localhost';
  const fullUrl = proto + '://' + host + (req.url || '/');

  const headers = new Headers();
  const raw = req.headers || {};
  for (const name of Object.keys(raw)) {
    const value = raw[name];
    if (Array.isArray(value)) {
      for (const v of value) headers.append(name, v);
    } else if (value !== undefined && value !== null) {
      headers.set(name, String(value));
    }
  }

  let body = null;
  const method = (req.method || 'GET').toUpperCase();
  if (method !== 'GET' && method !== 'HEAD') {
    body = new ReadableStream({
      start: (controller) => {
        req.on('data', (chunk) => controller.enqueue(new Uint8Array(chunk)));
        req.on('end', () => { try { controller.close(); } catch (_) {} });
        req.on('error', (err) => { try { controller.error(err); } catch (_) {} });
      },
    });
  }

  // duplex: 'half' 是 Node 构造带流式 body 的 Request 时的必传项
  const init = { method: method, headers: headers };
  if (body) { init.body = body; init.duplex = 'half'; }
  return new Request(fullUrl, init);
}

async function writeWebResponse(response, res) {
  res.statusCode = response.status;
  if (response.statusText) {
    try { res.statusMessage = response.statusText; } catch (_) {}
  }
  // Headers：用 forEach 而不是 entries，跨 Node 版本更稳
  response.headers.forEach((value, name) => {
    try { res.setHeader(name, value); } catch (_) {}
  });

  if (!response.body) {
    res.end();
    return;
  }

  const reader = response.body.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (value && value.length) {
        const ok = res.write(Buffer.from(value));
        if (!ok) await new Promise((r) => res.once('drain', r));
      }
    }
  } finally {
    res.end();
  }
}

function adaptWebHandler(fetchHandler) {
  return async (req, res) => {
    try {
      const webReq = buildWebRequest(req);
      const webRes = await fetchHandler(webReq);
      if (!webRes || typeof webRes.headers !== 'object' || typeof webRes.status !== 'number') {
        throw new Error('handler did not return a Response (got ' + Object.prototype.toString.call(webRes) + ')');
      }
      await writeWebResponse(webRes, res);
    } catch (err) {
      console.error('[backend-runtime] web handler error:', (err && err.stack) || err);
      if (!res.headersSent) {
        res.statusCode = 500;
        res.end('Internal Server Error');
      } else {
        try { res.end(); } catch (_) {}
      }
    }
  };
}

function collectMethodsFrom(obj) {
  if (!obj) return null;
  const out = {};
  let count = 0;
  for (const m of HTTP_METHODS) {
    if (typeof obj[m] === 'function') { out[m] = obj[m]; count++; }
  }
  return count > 0 ? out : null;
}

function pickMethodHandlers(mod) {
  // 优先 ESM 命名导出（mod 顶层）
  const top = collectMethodsFrom(mod);
  if (top) return top;
  // 回退看 CJS 互操作：module.exports = { GET, POST } 经 dynamic import 后挂在 mod.default 上
  return collectMethodsFrom(mod && mod.default);
}

function buildMethodRouter(methodHandlers) {
  const allow = Object.keys(methodHandlers).join(', ');
  return async (req, res) => {
    let method = (req.method || 'GET').toUpperCase();
    let handler = methodHandlers[method];
    // HEAD 退化到 GET（Node http 在 HEAD 时自动不发 body）
    if (!handler && method === 'HEAD' && methodHandlers.GET) {
      handler = methodHandlers.GET;
    }
    if (!handler) {
      res.statusCode = 405;
      res.setHeader('Allow', allow);
      res.end('Method Not Allowed');
      return;
    }
    return adaptWebHandler(handler)(req, res);
  };
}

// 检查 Node 版本是否足够（Web 全局变量是否可用）
function ensureWebGlobalsOrExit() {
  if (typeof globalThis.Request !== 'function' ||
      typeof globalThis.Response !== 'function' ||
      typeof globalThis.Headers !== 'function' ||
      typeof globalThis.ReadableStream !== 'function') {
    console.error('[backend-runtime] Web globals (Request/Response/Headers/ReadableStream) not available; need Node >= 18');
    process.exit(1);
  }
}

if (manifest.mode === 'direct') {
  if (!manifest.entry) {
    console.error('[backend-runtime] runtime.json missing "entry" for direct mode');
    process.exit(1);
  }

  // 优雅关闭机制：SIGTERM/SIGINT 收到后停止接受新连接，让 in-flight 请求自然完成，
  // 25s 后兜底强退（FC 默认 30s 后 SIGKILL，留 5s 余量）。
  let activeServer = null;
  let shuttingDown = false;
  const SHUTDOWN_TIMEOUT_MS = 25000;

  const gracefulShutdown = (signal) => {
    if (shuttingDown) return;
    shuttingDown = true;
    console.log('[backend-runtime] ' + signal + ' received, draining...');

    if (!activeServer) {
      process.exit(0);
      return;
    }

    const forceTimer = setTimeout(() => {
      console.error('[backend-runtime] graceful shutdown timed out after ' +
        SHUTDOWN_TIMEOUT_MS + 'ms, forcing exit');
      process.exit(1);
    }, SHUTDOWN_TIMEOUT_MS);
    forceTimer.unref();

    activeServer.close((err) => {
      clearTimeout(forceTimer);
      if (err) {
        console.error('[backend-runtime] server close error:', (err && err.message) || err);
        process.exit(1);
        return;
      }
      console.log('[backend-runtime] graceful shutdown complete');
      process.exit(0);
    });
  };

  // 1) 拦截 listen：复刻 Vercel @vercel/node 的策略
  //    不在第一次命中就 restore —— Fastify 等框架的 listen 是异步触发（Promise.then 链里），
  //    await import(entry) 返回时它可能还没 call listen，得给微任务一轮 / setImmediate 机会
  const Server = http.Server;
  const originalListen = Server.prototype.listen;
  let capturedServer = null;
  Server.prototype.listen = function () {
    if (!capturedServer) capturedServer = this; // 多次 listen 只认第一个
    return this; // 吞掉真实 bind
  };

  // 2) 加载用户入口（用 dynamic import，CJS/ESM 都通过这条路径——复刻 Vercel @vercel/node）
  let mod;
  try {
    const entryUrl = pathToFileURL(resolve(__dirname, manifest.entry)).href;
    mod = await import(entryUrl);
  } catch (err) {
    Server.prototype.listen = originalListen;
    console.error('[backend-runtime] failed to load entry:', (err && err.stack) || err);
    process.exit(1);
  }

  // 3) 给异步 listen 一个落地的机会：等一轮 microtask + 一轮 setImmediate
  //    Fastify/Hono node-server 等框架的 listen 在 await import 返回后才进 microtask 队列
  await new Promise((r) => setImmediate(r));
  await Promise.resolve();

  // 4) 还原 prototype，避免后续 createServer + listen(PORT) 也被吞
  Server.prototype.listen = originalListen;

  const exported = unwrapDefault(mod);
  // 命名 method 导出从原始 mod 上取（不要 unwrap，因为 named export 不会进 default）
  const methodHandlers = pickMethodHandlers(mod);

  const onReady = () => {
    console.log('[backend-runtime] listening on port ' + PORT);
  };
  const onError = (err) => {
    console.error('[backend-runtime] listen error:', err && err.message || err);
    process.exit(1);
  };

  // 派发优先级（与 Vercel 一致）：
  //   1. 命名 GET/POST/PUT/... 导出  → method router + Web adapter
  //   2. default 是含 fetch 方法的对象 → Web adapter
  //   3. default 是函数（Node 经典）   → 直接 wrap createServer
  //   4. require 期间捕获到 Server     → 复用捕获的 Server
  //   5. 都没有                       → 自管理，warn
  if (methodHandlers) {
    ensureWebGlobalsOrExit();
    const server = http.createServer(buildMethodRouter(methodHandlers));
    activeServer = server;
    server.on('error', onError);
    server.listen(PORT, onReady);
  } else if (exported && typeof exported === 'object' && typeof exported.fetch === 'function') {
    ensureWebGlobalsOrExit();
    const fetchFn = exported.fetch.bind(exported);
    const server = http.createServer(adaptWebHandler(fetchFn));
    activeServer = server;
    server.on('error', onError);
    server.listen(PORT, onReady);
  } else if (typeof exported === 'function') {
    // Node 经典风格：(req, res) => void
    // 注意：用户写 (request) => Response 也会落到这里 → 走经典模式 → 不能正常工作
    // 想用 Web 风格请用 { fetch } 或命名 GET/POST。这是 Vercel nodejs runtime 的同款约束。
    const server = http.createServer(exported);
    activeServer = server;
    server.on('error', onError);
    server.listen(PORT, onReady);
  } else if (capturedServer) {
    // app.listen 风格：用户在 require 期间调过 listen
    activeServer = capturedServer;
    capturedServer.on('error', onError);
    capturedServer.listen(PORT, onReady);
  } else {
    // 无导出 handler、无捕获 server。activeServer 保持 null，SIGTERM 只能 exit(0)。
    console.warn('[backend-runtime] no exported handler or captured server; entry presumed self-managed on PORT=' + PORT);
  }

  ['SIGTERM', 'SIGINT'].forEach((sig) => {
    process.on(sig, () => gracefulShutdown(sig));
  });
} else if (manifest.mode === 'fc-handlers') {
  // FC handler 模式：由 buildFcBundle 生成的 dispatcher。
  //   - 读 routes.json，按 priority 顺序匹配 URL
  //   - 命中后 require 对应文件 + handlerCache 缓存（懒加载）
  //   - 派发逻辑同 direct 模式：method 命名导出 / { fetch } / function
  //     但这里不允许"用户代码自己 listen"那条路径（每个文件不是独立 server）
  ensureWebGlobalsOrExit();

  const routesPath = join(__dirname, 'routes.json');
  let routes;
  try {
    routes = JSON.parse(readFileSync(routesPath, 'utf-8'));
  } catch (err) {
    console.error('[backend-runtime] failed to read routes.json:', (err && err.message) || err);
    process.exit(1);
  }
  if (!Array.isArray(routes)) {
    console.error('[backend-runtime] routes.json is not an array');
    process.exit(1);
  }

  // 编译 PCRE
  const compiledRoutes = routes.map((r) => ({
    re: new RegExp(r.pattern),
    file: r.file,
    paramNames: Array.isArray(r.paramNames) ? r.paramNames : [],
  }));

  // handlerCache：value 是 Promise<resolved>，首次请求触发 dynamic import + 形状识别，
  // 之后所有命中此文件的请求复用同一个 Promise（并发请求不会重复 import）
  const handlerCache = Object.create(null);

  async function compileFcUserCode(absPath) {
    const url = pathToFileURL(absPath).href;
    const mod = await import(url);
    const exported = unwrapDefault(mod);
    const methodHandlers = pickMethodHandlers(mod);

    if (methodHandlers) return buildMethodRouter(methodHandlers);
    if (exported && typeof exported === 'object' && typeof exported.fetch === 'function') {
      return adaptWebHandler(exported.fetch.bind(exported));
    }
    if (typeof exported === 'function') return exported;
    throw new Error('Cannot detect handler shape in ' + absPath +
      ' (need named GET/POST..., default { fetch }, or default function(req, res))');
  }

  const dispatcher = async (req, res) => {
    try {
      const url = new URL(req.url || '/', 'http://x');
      const pathname = url.pathname;

      for (const route of compiledRoutes) {
        const m = pathname.match(route.re);
        if (!m) continue;

        // 注入参数到 query string，再回写到 req.url；用户用 req.query.id / new URL(req.url).searchParams 都能拿到
        for (let i = 0; i < route.paramNames.length; i++) {
          const v = m[i + 1];
          if (v !== undefined) url.searchParams.set(route.paramNames[i], v);
        }
        req.url = url.pathname + (url.search || '');

        if (!handlerCache[route.file]) {
          handlerCache[route.file] = compileFcUserCode(resolve(__dirname, route.file))
            .catch((err) => {
              // 编译失败的入口从缓存里清掉，下次请求重试
              delete handlerCache[route.file];
              throw err;
            });
        }
        const handler = await handlerCache[route.file];
        return handler(req, res);
      }

      res.statusCode = 404;
      res.end('Not Found');
    } catch (err) {
      console.error('[backend-runtime] dispatcher error:', (err && err.stack) || err);
      if (!res.headersSent) {
        res.statusCode = 500;
        res.end('Internal Server Error');
      } else {
        try { res.end(); } catch (_) {}
      }
    }
  };

  let activeServer = null;
  let shuttingDown = false;
  const SHUTDOWN_TIMEOUT_MS = 25000;
  const gracefulShutdown = (signal) => {
    if (shuttingDown) return;
    shuttingDown = true;
    console.log('[backend-runtime] ' + signal + ' received, draining...');
    if (!activeServer) { process.exit(0); return; }
    const forceTimer = setTimeout(() => {
      console.error('[backend-runtime] graceful shutdown timed out, forcing exit');
      process.exit(1);
    }, SHUTDOWN_TIMEOUT_MS);
    forceTimer.unref();
    activeServer.close((err) => {
      clearTimeout(forceTimer);
      if (err) {
        console.error('[backend-runtime] server close error:', err && err.message || err);
        process.exit(1);
        return;
      }
      console.log('[backend-runtime] graceful shutdown complete');
      process.exit(0);
    });
  };

  const server = http.createServer(dispatcher);
  activeServer = server;
  server.on('error', (err) => {
    console.error('[backend-runtime] listen error:', err && err.message || err);
    process.exit(1);
  });
  server.listen(PORT, () => {
    console.log('[backend-runtime] dispatcher listening on port ' + PORT +
      ' (' + compiledRoutes.length + ' routes)');
  });

  ['SIGTERM', 'SIGINT'].forEach((sig) => {
    process.on(sig, () => gracefulShutdown(sig));
  });
} else if (manifest.mode === 'spawn') {
  if (!Array.isArray(manifest.command) || manifest.command.length === 0) {
    console.error('[backend-runtime] runtime.json missing "command" array for spawn mode');
    process.exit(1);
  }
  const [cmd, ...args] = manifest.command;
  const resolved = cmd === 'node' ? process.execPath : cmd;
  const child = spawn(resolved, args, { stdio: 'inherit', cwd: cwdAbs, env: process.env });
  child.on('exit', (code, signal) => {
    if (signal) process.kill(process.pid, signal);
    else process.exit(code == null ? 0 : code);
  });
  ['SIGINT', 'SIGTERM'].forEach((sig) => {
    process.on(sig, () => { try { child.kill(sig); } catch (_) {} });
  });
} else {
  console.error('[backend-runtime] unknown mode: ' + manifest.mode);
  process.exit(1);
}
